name: Sample
on: push

jobs: 
  lint: 
    name: Codelint
    runs-on: ubuntu-16.04
    steps:
      - name: checkout    
        uses: actions/checkout@v2
        fetch-depth: 1
      - name: list
        run: ls -al
        shell: bash
      - name: echo
        run: echo $PATH
        shell: bash